# Generated by Django 4.1.7 on 2023-03-13 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ingredient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('long_life', models.BooleanField(blank=True, null=True)),
                ('shelf_life', models.IntegerField(blank=True, null=True)),
                ('substitutes', models.CharField(blank=True, max_length=200, null=True)),
                ('category', models.CharField(blank=True, max_length=60, null=True)),
                ('calories', models.IntegerField(default=0)),
                ('carbohydrates', models.FloatField(default=0)),
                ('sugar', models.FloatField(default=0)),
                ('fat', models.FloatField(default=0)),
                ('protein', models.FloatField(default=0)),
                ('fibre', models.FloatField(default=0)),
                ('typical_weight', models.IntegerField(blank=True, null=True)),
            ],
        ),
    ]
