# Generated by Django 4.1.7 on 2023-03-11 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cupboard', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ingredient',
            name='calories',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ingredient',
            name='category',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
        migrations.AddField(
            model_name='ingredient',
            name='fat',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ingredient',
            name='fibre',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ingredient',
            name='long_life',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ingredient',
            name='protein',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ingredient',
            name='shelf_life',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
