# Generated by Django 4.1.7 on 2023-03-11 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cupboard', '0002_ingredient_calories_ingredient_category_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ingredient',
            name='substitutes',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
