# Generated by Django 4.1.7 on 2023-03-30 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cupboard', '0002_alter_ingredient_category_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredient',
            name='long_life',
            field=models.BooleanField(default=True),
        ),
    ]
