# Generated by Django 4.1.7 on 2023-03-11 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cupboard', '0003_ingredient_substitutes'),
    ]

    operations = [
        migrations.AddField(
            model_name='ingredient',
            name='typical_weight',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
