# Generated by Django 4.1.7 on 2023-03-30 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cupboard', '0003_alter_ingredient_long_life'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredient',
            name='typical_weight',
            field=models.IntegerField(default=0),
        ),
    ]
