# Generated by Django 4.1.7 on 2023-03-30 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cupboard', '0004_alter_ingredient_typical_weight'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredient',
            name='shelf_life',
            field=models.IntegerField(default=14),
        ),
    ]
