# Generated by Django 4.1.7 on 2023-03-11 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cupboard', '0004_ingredient_typical_weight'),
    ]

    operations = [
        migrations.AddField(
            model_name='ingredient',
            name='carbohydrates',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ingredient',
            name='sugar',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
