# Generated by Django 4.1.6 on 2023-02-26 10:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cupboard', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('method', models.TextField(blank=True, max_length=5000, null=True)),
                ('ingredients_string', models.TextField(blank=True, max_length=1000, null=True)),
                ('book', models.CharField(blank=True, max_length=200, null=True)),
                ('page', models.CharField(blank=True, max_length=5, null=True)),
                ('serves', models.CharField(blank=True, max_length=5, null=True)),
                ('description', models.TextField(blank=True, max_length=500, null=True)),
                ('url', models.URLField(blank=True, null=True)),
                ('jumbled_input', models.TextField(blank=True, max_length=8000, null=True)),
                ('simplified_ingredients', models.TextField(blank=True, max_length=1000, null=True)),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('uses_ingredient', models.ManyToManyField(related_name='ingredient_uses', to='cupboard.ingredient')),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ingredients_owned', models.ManyToManyField(related_name='owned_by_profile', to='cupboard.ingredient')),
                ('ingredients_referenced', models.ManyToManyField(related_name='referenced_by_profile', to='cupboard.ingredient')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
