# Generated by Django 4.1.7 on 2023-03-13 16:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cupboard', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ai_credits_used', models.IntegerField(default=0)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ProfileIngredient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('in_stock', models.BooleanField(default=False)),
                ('date_added', models.DateTimeField(default=django.utils.timezone.now)),
                ('expiry_date', models.DateField(blank=True, null=True)),
                ('ingredient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='profile_ingredient', to='cupboard.ingredient')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='profile_ingredient', to='recipes.profile')),
            ],
            options={
                'ordering': ['-expiry_date'],
                'get_latest_by': 'expiry_date',
            },
        ),
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('method', models.TextField(blank=True, max_length=5000, null=True)),
                ('ingredients_string', models.TextField(blank=True, max_length=1000, null=True)),
                ('simplified_ingredients', models.TextField(blank=True, max_length=1000, null=True)),
                ('book', models.CharField(blank=True, max_length=200, null=True)),
                ('page', models.CharField(blank=True, max_length=5, null=True)),
                ('serves', models.CharField(blank=True, max_length=5, null=True)),
                ('serves_int', models.IntegerField(blank=True, null=True)),
                ('description', models.TextField(blank=True, max_length=500, null=True)),
                ('url', models.URLField(blank=True, null=True)),
                ('jumbled_input', models.TextField(blank=True, max_length=8000, null=True)),
                ('from_photo', models.BooleanField(default=False)),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='RecipeIngredient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.FloatField(blank=True, null=True)),
                ('measurement_unit', models.CharField(blank=True, max_length=50, null=True)),
                ('local_name', models.CharField(max_length=100)),
                ('position_in_list', models.IntegerField(blank=True, null=True)),
                ('optional', models.BooleanField(default=False)),
                ('alternative', models.BooleanField(default=False)),
                ('ingredient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recipe_ingredient', to='recipes.profileingredient')),
                ('recipe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recipe_ingredient', to='recipes.recipe')),
            ],
        ),
    ]
