# Generated by Django 4.1.6 on 2023-02-26 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cupboard', '0001_initial'),
        ('recipes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='ingredients_owned',
            field=models.ManyToManyField(blank=True, related_name='owned_by_profile', to='cupboard.ingredient'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='ingredients_referenced',
            field=models.ManyToManyField(blank=True, related_name='referenced_by_profile', to='cupboard.ingredient'),
        ),
    ]
