# Generated by Django 4.1.7 on 2023-03-13 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cupboard', '0001_initial'),
        ('recipes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='last_20_expired_items',
            field=models.ManyToManyField(blank=True, related_name='last_20_expired_items', to='cupboard.ingredient'),
        ),
        migrations.AlterUniqueTogether(
            name='profileingredient',
            unique_together={('profile', 'ingredient')},
        ),
    ]
