# Generated by Django 4.1.6 on 2023-02-26 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0002_alter_profile_ingredients_owned_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='ai_credits_used',
            field=models.IntegerField(default=0),
        ),
    ]
