# Generated by Django 4.1.6 on 2023-02-06 16:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0002_recipe_book_recipe_description_recipe_page_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recipe',
            old_name='recipe_method',
            new_name='method',
        ),
        migrations.RenameField(
            model_name='recipe',
            old_name='recipe_name',
            new_name='name',
        ),
    ]
