# Generated by Django 4.1.7 on 2023-03-14 14:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0002_profile_last_20_expired_items_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recipeingredient',
            old_name='ingredient',
            new_name='profile_ingredient',
        ),
    ]
