# Generated by Django 4.1.6 on 2023-02-28 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0003_profile_ai_credits_used'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='from_photo',
            field=models.BooleanField(default=False),
        ),
    ]
