# Generated by Django 4.1.7 on 2023-03-30 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0004_profileingredient_locally_modified'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='book',
            field=models.CharField(blank=True, default='', max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='recipe',
            name='description',
            field=models.TextField(blank=True, default='', max_length=500),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='recipe',
            name='ingredients_string',
            field=models.TextField(blank=True, default='', max_length=1000),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='recipe',
            name='jumbled_input',
            field=models.TextField(blank=True, default='', max_length=8000),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='recipe',
            name='method',
            field=models.TextField(blank=True, default='', max_length=5000),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='recipe',
            name='page',
            field=models.CharField(blank=True, default='', max_length=5),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='recipe',
            name='serves',
            field=models.CharField(blank=True, default='', max_length=5),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='recipe',
            name='simplified_ingredients',
            field=models.TextField(blank=True, default='', max_length=1000),
            preserve_default=False,
        ),
    ]
