# Generated by Django 4.1.7 on 2023-03-03 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0005_recipeingredient'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recipeingredient',
            old_name='string',
            new_name='local_name',
        ),
        migrations.AddField(
            model_name='recipeingredient',
            name='optional',
            field=models.BooleanField(default=True),
        ),
    ]
