# Generated by Django 4.1.7 on 2023-03-30 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0005_alter_recipe_book_alter_recipe_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipeingredient',
            name='measurement_unit',
            field=models.CharField(blank=True, default='', max_length=50),
            preserve_default=False,
        ),
    ]
