# Generated by Django 4.1.6 on 2023-02-09 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0005_recipe_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='jumbled_input',
            field=models.TextField(blank=True, max_length=8000, null=True),
        ),
        migrations.AddField(
            model_name='recipe',
            name='simplified_ingredients',
            field=models.TextField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='description',
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='ingredients_string',
            field=models.TextField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='method',
            field=models.TextField(max_length=5000),
        ),
    ]
