# Generated by Django 4.1.7 on 2023-03-30 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0006_alter_recipeingredient_measurement_unit'),
    ]

    operations = [
        migrations.AddField(
            model_name='profileingredient',
            name='calories_override',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='profileingredient',
            name='carbohydrates_override',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='profileingredient',
            name='category_override',
            field=models.CharField(blank=True, max_length=60),
        ),
        migrations.AddField(
            model_name='profileingredient',
            name='fat_override',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='profileingredient',
            name='fibre_override',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='profileingredient',
            name='long_life_override',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='profileingredient',
            name='protein_override',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='profileingredient',
            name='shelf_life_override',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='profileingredient',
            name='substitutes_override',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='profileingredient',
            name='sugar_override',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='profileingredient',
            name='typical_weight_override',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
