# Generated by Django 4.1.6 on 2023-02-10 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0006_recipe_jumbled_input_recipe_simplified_ingredients_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredient',
            name='ingredient_uses',
            field=models.ManyToManyField(related_name='uses_ingredient', to='recipes.recipe'),
        ),
    ]
