# Generated by Django 4.1.7 on 2023-03-30 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0007_profileingredient_calories_override_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profileingredient',
            name='locally_modified',
        ),
        migrations.AddField(
            model_name='profile',
            name='ai_credits',
            field=models.IntegerField(default=0),
        ),
    ]
