# Generated by Django 4.1.7 on 2023-03-09 16:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0008_alter_recipeingredient_unique_together'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipe',
            name='uses_ingredient',
        ),
    ]
