# Generated by Django 4.1.7 on 2023-03-11 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0009_remove_recipe_uses_ingredient'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='serves_int',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
