# Generated by Django 4.1.6 on 2023-02-13 10:58

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('recipes', '0011_rename_ingredient_name_ingredient_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ingredient',
            name='ingredient_cupboards',
        ),
        migrations.AddField(
            model_name='ingredient',
            name='in_cupboard',
            field=models.ManyToManyField(default='admin', related_name='owns_ingredient', to=settings.AUTH_USER_MODEL),
        ),
    ]
