# Generated by Django 4.1.6 on 2023-02-13 11:10

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('recipes', '0015_alter_ingredient_in_recipes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredient',
            name='in_cupboard',
            field=models.ManyToManyField(related_name='owns_ingredient', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='ingredient',
            name='in_recipes',
            field=models.ManyToManyField(related_name='owned_ingredient', to=settings.AUTH_USER_MODEL),
        ),
    ]
