# Generated by Django 4.1.6 on 2023-02-21 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0021_remove_mealplan_user_mealplan_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='mealplan',
            name='ingredients',
            field=models.ManyToManyField(to='recipes.ingredient'),
        ),
    ]
